SELECT *
WHERE
{
?director <http://dbpedia.org/ontology/nationality> <http://dbpedia.org/resource/Italy> .
?film <http://dbpedia.org/ontology/director> ?director .
?x <http://www.w3.org/2002/07/owl#sameAs> ?film .
}