SELECT ?caff ?lab WHERE {
    {
        <http://www4.wiwiss.fu-berlin.de/drugbank/resource/drugs/DB00201> <http://www.w3.org/2002/07/owl#sameAs> ?caff .
         ?caff <http://www.w3.org/2000/01/rdf-schema#label> ?lab .
    }
    OPTIONAL
    {
        ?caff ?s <http://dbpedia.org/resource/Category:Anxiogenics> .
    }
}