SELECT  *
WHERE
  {   { { SERVICE <http://aifb-ls3-remus.aifb.kit.edu:8890/sparql>
            { ?director  <http://dbpedia.org/ontology/nationality>  <http://dbpedia.org/resource/Italy> .
              { ?film  <http://dbpedia.org/ontology/director>  ?director .}
            }
          { SERVICE <http://aifb-ls3-remus.aifb.kit.edu:8897/sparql>
              { ?x  <http://www.w3.org/2002/07/owl#sameAs>  ?film .
                { ?x  <http://xmlns.com/foaf/0.1/based_near>  ?y .}
              }
          }
        }
        { SERVICE <http://aifb-ls3-remus.aifb.kit.edu:8894/sparql>
            { ?y  <http://www.geonames.org/ontology#officialName>  ?n .}
        }
      }
    UNION
      { { SERVICE <http://aifb-ls3-remus.aifb.kit.edu:8890/sparql>
            { ?director  <http://dbpedia.org/ontology/nationality>  <http://dbpedia.org/resource/Italy> .
              { ?film  <http://dbpedia.org/ontology/director>  ?director .}
            }
          { SERVICE <http://aifb-ls3-remus.aifb.kit.edu:8898/sparql>
              { ?x  <http://xmlns.com/foaf/0.1/based_near>  ?y .
                { ?x  <http://www.w3.org/2002/07/owl#sameAs>  ?film .}
              }
          }
        }
        { SERVICE <http://aifb-ls3-remus.aifb.kit.edu:8894/sparql>
            { ?y  <http://www.geonames.org/ontology#officialName>  ?n .}
        }
      }
  }