SELECT *
WHERE
{
?s <http://swrc.ontoware.org/ontology#isbn> ?o1 .
?s <http://purl.org/dc/elements/1.1/creator> <http://dblp.l3s.de/d2r/resource/authors/Abdullah_Uz_Tansel> .
?s <http://purl.org/dc/elements/1.1/publisher> ?o3 .
?s <http://swrc.ontoware.org/ontology#editor> ?editor .
?editor <http://xmlns.com/foaf/0.1/name> ?name .
?editor <http://xmlns.com/foaf/0.1/homepage> ?hp .
}